services:
  migrations:
    container_name: migrations
    build:
      dockerfile: ./deployment/Dockerfile
      context: ./backend/
    environment:
      IN_DOCKER_CONTAINER: "true"
    command: ["/app/migrations"]
    depends_on:
      postgres:
        condition: service_healthy
  server:
    container_name: server
    build:
      dockerfile: ./deployment/Dockerfile
      context: ./backend/
    environment:
      IN_DOCKER_CONTAINER: "true"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    entrypoint: ["/app/server"]
    depends_on:
      migrations:
        condition: service_completed_successfully
  postgres:
    image: postgres:17.4
    container_name: ztp-db
    restart: always
    env_file: ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ztp_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      retries: 3

volumes:
  ztp_data:

