services:
  migrations:
    container_name: migrations
    build:
      dockerfile: ../deployment/go/Dockerfile
      context: ./backend/go
    env_file: ".env"
    command: ["/app/migrations"]
    depends_on:
      postgres:
        condition: service_healthy
  server:
    container_name: server
    build:
      dockerfile: ../deployment/go/Dockerfile
      context: ./backend/go
    env_file: ".env"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    entrypoint: ["/app/server"]
    depends_on:
      migrations:
        condition: service_completed_successfully
  scheduler:
    container_name: scheduler
    build:
      dockerfile: ../deployment/python/scheduler/Dockerfile
      context: ./backend/python
    env_file: ".env"
    entrypoint: ["python", "main.py"]
    depends_on:
      migrations:
        condition: service_completed_successfully
  ocr-worker:
    container_name: ocr-worker
    build:
      dockerfile: ../deployment/python/ocr/Dockerfile
      context: ./backend/python
    env_file: ".env"
    entrypoint: ["python", "main.py"]
    depends_on:
      migrations:
        condition: service_completed_successfully
      scheduler:
        condition: service_started
  initializer:
    container_name: initializer
    build:
      context: ./backend/deployment/initializer
    depends_on:
      migrations:
        condition: service_completed_successfully
      server:
        condition: service_started
  postgres:
    image: postgres:17.4
    container_name: ztp-db
    restart: always
    env_file: ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ztp_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      retries: 3
  localstack:
    image: localstack/localstack
    container_name: localstack
    env_file: ".env"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./backend/deployment/scripts/aws/create_aws_services.sh:/etc/localstack/init/ready.d/create_aws_services.sh
volumes:
  ztp_data:
  localstack_data:
