// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, name, surname, username, email, password, phone_number, user_role)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddUserParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Surname     *string   `json:"surname"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Password    string    `json:"password"`
	PhoneNumber string    `json:"phone_number"`
	UserRole    UserRole  `json:"user_role"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.UserRole,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, name, surname, username, email, password, phone_number, user_role
FROM
    users u
WHERE
    u.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.UserRole,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, name, surname, username, email, password, phone_number, user_role
FROM
    users u
WHERE
    u.id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.UserRole,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id, name, surname, username, email, password, phone_number, user_role
FROM
    users u
WHERE
    u.username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.UserRole,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id, name, surname, username, email, password, phone_number, user_role
FROM
    users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
select u.id, u.username, u.password from users u where u.username = $1
`

type UserExistsRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Password string    `json:"password"`
}

func (q *Queries) UserExists(ctx context.Context, username string) (UserExistsRow, error) {
	row := q.db.QueryRow(ctx, userExists, username)
	var i UserExistsRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
