version: "2"
formatters:
  enable:
    - gofumpt
    - gci
    - goimports
    - golines
linters:
  default: fast
  enable:
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errname
    - exhaustive
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nilerr
    - paralleltest
    - prealloc
    - reassign
    - staticcheck
    - unconvert
    - unparam
    - unused
