// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcrepositiories

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID                 uuid.UUID `json:"id"`
	Title              *string   `json:"title"`
	Url                string    `json:"url"`
	OcrContent         *string   `json:"ocr_content"`
	DocumentTypeID     uuid.UUID `json:"document_type_id"`
	DocumentCategoryID uuid.UUID `json:"document_category_id"`
}

type DocumentCategory struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

type DocumentType struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

type Job struct {
	ID         uuid.UUID          `json:"id"`
	Status     *string            `json:"status"`
	UserID     pgtype.UUID        `json:"user_id"`
	DocumentID uuid.UUID          `json:"document_id"`
	StartedAt  time.Time          `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	Name        *string     `json:"name"`
	Surname     *string     `json:"surname"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	PhoneNumber string      `json:"phone_number"`
	Role        interface{} `json:"role"`
}

type UserDocument struct {
	UserID     uuid.UUID `json:"user_id"`
	DocumentID uuid.UUID `json:"document_id"`
}
