// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, status, document_id, started_at)
    VALUES ($1, $2, $3, $4)
`

type CreateJobParams struct {
	ID         uuid.UUID `json:"id"`
	Status     *string   `json:"status"`
	DocumentID uuid.UUID `json:"document_id"`
	StartedAt  time.Time `json:"started_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.ID,
		arg.Status,
		arg.DocumentID,
		arg.StartedAt,
	)
	return err
}
