name: Backend CI
on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'
jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Install dependencies
        run: make install
        env:
          GOBIN: ${{ github.workspace }}/bin
      - name: Add tools to path
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.50.0
      - name: Verify Buf installation
        run: buf --version
      - name: Check sql generated files
        run: sqlc diff
      - name: Generate mocks and sql.go files
        run: make generate
      - name: Run unit tests
        run: make test
      - name: Run linting
        run: make lint
